Boolean Masks

In [1]:
import numpy as np

In [4]:
np.random.seed(seed=24) # set the seed to 24
# create 100 sized array of random numbers from 1 to 5
random_integers = np.random.randint(low=1, high=5, size=100) 

In [9]:
random_integers[:5] # prints first 5 elements of array

array([3, 4, 1, 4, 2])

In [11]:
# need to know locations of all elements of random_integers equal to 3 
# Need to create a Boolean mask for this 
is_equal_to_3 = random_integers == 3
is_equal_to_3[:5] 

array([ True, False, False, False, False])

In [12]:
# The amount of elements in the array that are equal to 3
sum(is_equal_to_3)

22

In [13]:
# Displays all elements that are equal to 3
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])